name: mytailmate
description: My Tail Mate

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  get_cli: ^1.8.1
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.0.3
  smooth_page_indicator: ^1.0.0+2
  intl_phone_field: ^3.1.0
  otp_text_field: ^1.1.3
  roundcheckbox: ^2.0.5
  carousel_slider: ^4.1.1
  tab_container: ^2.0.0
  readmore: ^2.2.0
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_sliders: ^20.2.49
  card_swiper: ^2.0.4
  youtube_player_flutter: ^8.1.0
  im_stepper: ^1.0.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/gif/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Placard Condensed
      fonts:
        - asset: assets/fonts/PlacardCondensed.ttf
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Medium.ttf
          weight: 500
        - asset: assets/fonts/Mulish-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mulish-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-ExtraBold.ttf
          weight: 800
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
